language: c
install: wget https://raw.githubusercontent.com/yomimono/ocaml-ci-scripts/extra-env/.travis-docker.sh #fork needed for extra_env, github pr#160
script: bash -ex .travis-docker.sh
sudo: required
services:
  - docker
sudo: false
env:
 global:
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
   - POST_INSTALL_HOOK="sh ./.travis-ci.sh"
     # tcpip pin needed for tcpip.xen linking fix, yet unreleased -yomimono
     # charrua pins needed until v0.9 release -yomimono
   - PINS="tcpip.dev:--dev functoria.dev:--dev functoria-runtime.dev:--dev mirage.dev:. mirage-types.dev:. mirage-types-lwt.dev:. mirage-runtime.dev:. charrua-core.dev:--dev charrua-client.dev:https://github.com/mirage/charrua-core.git charrua-client-lwt.dev:https://github.com/mirage/charrua-core.git charrua-client-mirage.dev:https://github.com/mirage/charrua-core.git"
   - TESTS=false #testing via travis-ci.sh
 matrix:
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.04.2 EXTRA_ENV="MODE=xen"
   - PACKAGE=mirage DISTRO=debian-testing OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=ukvm"
   - PACKAGE=mirage DISTRO=debian-unstable OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=unix"
     PINS="functoria.dev:--dev functoria-runtime.dev:--dev mirage.dev:. mirage-types.dev:. mirage-types-lwt.dev:. mirage-runtime.dev:. nocrypto.dev:https://github.com/samoht/ocaml-nocrypto.git#nocrypto-mirage charrua-core.dev:--dev charrua-client.dev:https://github.com/mirage/charrua-core.git charrua-client-lwt.dev:https://github.com/mirage/charrua-core.git charrua-client-mirage.dev:https://github.com/mirage/charrua-core.git tcpip.dev:--dev"
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.04.2 EXTRA_ENV="MODE=xen"
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=ukvm"
   - PACKAGE=mirage DISTRO=centos-7 OCAML_VERSION=4.04.2 EXTRA_ENV="MODE=virtio"
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.04.2 EXTRA_ENV="MODE=xen"
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.04.2 EXTRA_ENV="MODE=ukvm"
   - PACKAGE=mirage DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0 EXTRA_ENV="MODE=virtio"
