language: c
sudo: required
install: wget https://raw.githubusercontent.com/dsheets/ocaml-travisci-skeleton/yorick/.travis-opam.sh
script: bash -ex .travis-ci.sh
env:
  - OCAML_VERSION=4.02 PACKAGE=mirage
  - OCAML_VERSION=4.01 PACKAGE=mirage
  - OCAML_VERSION=4.01 PACKAGE=mirage-types REV_DEPS=*
