language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-ci.sh
env:
  global:
          - PINS="mirage-skeleton.dev:https://github.com/mirage/mirage-skeleton.git tcpip:https://github.com/yomimono/mirage-tcpip.git#icmp_refactor"
  matrix:
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.02 PACKAGE=mirage
  - UPDATE_GCC_BINUTILS=1 OCAML_VERSION=4.02 PACKAGE=mirage-types
